<?php

# Nayythan
echo "ayy lmao\n";

# BUCKO
#YOU MUST ECHO "ayy lmao"
echo "ayy lmao";
#YOU MUST ALSO ECHO A NEW LINE
echo "\n";
#IF YOU NEED HELP PLEASE DO NOT MESSAGE ME. THAT'S WHAT STACK OVERFLOW IS FOR.

#FAILURE TO COMPLY WITH THESE RULES WILL GET YOU REPORTED MY DAD WORKS AT GITHUB
